=== ViViVerse/VVVCreator/TargetCreation/Template/Template.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Template"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="Template">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Description" type="xs:string" />
        <xs:element name="TargetFolderHint" type="xs:string" />
        <xs:element name="MacroDefinitions">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="MacroDefinition" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name" type="xs:string" />
                    <xs:element name="Type">
                      <xs:annotation>
                        <xs:documentation>The type of the macro.&lt;br/&gt;Apart from UserString, all other macros will be generated by the system.</xs:documentation>
                      </xs:annotation>
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="SysDate">
                            <xs:annotation>
                              <xs:documentation>The current date in the format yyyy-MM-dd.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                          <xs:enumeration value="SysGuid">
                            <xs:annotation>
                              <xs:documentation>A new guid in the format {00000000-0000-0000-0000-000000000000}.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                          <xs:enumeration value="SysCodeGuid">
                            <xs:annotation>
                              <xs:documentation>A new guid in the format 00000000, 0000, 0000, 0000, 000000000000.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                          <xs:enumeration value="UserString">
                            <xs:annotation>
                              <xs:documentation>A string which has to be provided by the user.</xs:documentation>
                            </xs:annotation>
                          </xs:enumeration>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Description" type="xs:string" />
                    <xs:element name="Value" type="xs:string" minOccurs="0">
                      <xs:annotation>
                        <xs:documentation>An optional default value.</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ViViVerse/VVVCreator/TargetCreation/Template/MobaCanSensor/Template.xml
<?xml version="1.0" encoding="utf-8"?>
<Template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Template.xsd">
  <Description>Creates a MOBA CAN sensor with a single measurement value message id.</Description>
  <TargetFolderHint>Choose the collection project folder as target folder.</TargetFolderHint>
  <MacroDefinitions>
    <MacroDefinition>
      <Name>SENSOR_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the sensor in lower case. Must not contain whitespace. Example: slope_sensor or wire_rope</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>FAMILY_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the family to which the sensor belongs, without the leading 'family_'. This depends on what the sensor is measuring. Look into symbiosis libraries for available families. Example: length_sensor</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>CAN_MSG_ID</Name>
      <Type>UserString</Type>
      <Description>The id of the CAN message which contains the measurement value. Example: 0x00AA</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>MEAS_DIM</Name>
      <Type>UserString</Type>
      <Description>The phsysical dimension measured by the sensor. This is the type of the main metabolic of the family. Example: length or angle</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>MSG_ID_NAME</Name>
      <Type>UserString</Type>
      <Description>An abbreviated name which is appended to 'can_msg_id_'. Example: rot or len</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>OBJECT_NAME</Name>
      <Type>UserString</Type>
      <Description>The name with which the sensor appears in the agora and demiurg. Example: MobaRotation</Description>
    </MacroDefinition>
  </MacroDefinitions>
</Template>

=== ViViVerse/VVVCreator/TargetCreation/Template/OrganelleCommonLibrary/Template.xml
<?xml version="1.0" encoding="utf-8"?>
<Template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Template.xsd">
  <Description>Creates a common organelle library which can be used within its package but also by other packages.</Description>
  <TargetFolderHint>Choose the organelle folder of a package as target folder.</TargetFolderHint>
  <MacroDefinitions>
    <MacroDefinition>
      <Name>PACKAGE_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the package which contains the common organelle library. Must not contain whitespace.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>LIBRARY_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the common organelle library. Must not contain whitespace.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>UND_LIBRARY_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the library without prefix like 'vvv_'. Must not contain whitespace.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>COPYRIGHT</Name>
      <Type>UserString</Type>
      <Description>The copyright string for the file headers.</Description>
    </MacroDefinition>
  </MacroDefinitions>
</Template>

=== ViViVerse/VVVCreator/TargetCreation/Template/Family/Template.xml
<?xml version="1.0" encoding="utf-8"?>
<Template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Template.xsd">
  <Description>Creates a family to be included in a symbiosis project.</Description>
  <TargetFolderHint>Choose the symbiosis project folder as target folder.</TargetFolderHint>
  <MacroDefinitions>
    <MacroDefinition>
      <Name>FAMILY_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the family in lower case, without the leading 'family_'. Must not contain whitespace. Example: slope_sensor or thermostat</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>PACKAGE_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the package to which the family will be added. Example: vvv_base</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>COPYRIGHT</Name>
      <Type>UserString</Type>
      <Description>The copyright string for the file headers.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>HAS_COMMANDS</Name>
      <Type>UserString</Type>
      <Description>If true, the code for providing commands is added.</Description>
      <Value>true</Value>
    </MacroDefinition>
    <MacroDefinition>
      <Name>HAS_SYNCHRONOUS_COMMANDS</Name>
      <Type>UserString</Type>
      <Description>If true, the code for providing an example synchronous command is added. HAS_COMMANDS must be set to true as well.</Description>
      <Value>true</Value>
    </MacroDefinition>
    <MacroDefinition>
      <Name>HAS_ASYNCHRONOUS_COMMANDS</Name>
      <Type>UserString</Type>
      <Description>If true, the code for providing an example asynchronous command is added. HAS_COMMANDS must be set to true as well.</Description>
      <Value>true</Value>
    </MacroDefinition>
    <MacroDefinition>
      <Name>HAS_METABOLICS</Name>
      <Type>UserString</Type>
      <Description>If true, the code for providing an example metabolic is added.</Description>
      <Value>true</Value>
    </MacroDefinition>
    <MacroDefinition>
      <Name>HAS_GENES</Name>
      <Type>UserString</Type>
      <Description>If true, the code for providing an example gene is added.</Description>
      <Value>true</Value>
    </MacroDefinition>
  </MacroDefinitions>
</Template>

=== ViViVerse/VVVCreator/TargetCreation/Template/Package/Template.xml
<?xml version="1.0" encoding="utf-8"?>
<Template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Template.xsd">
  <Description>Creates an entire VVV package.</Description>
  <TargetFolderHint>Choose the ViViVerse/software/package folder as target folder.</TargetFolderHint>
  <MacroDefinitions>
    <MacroDefinition>
      <Name>PACKAGE_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the package. Must not contain whitespace.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>UND_PACKAGE_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the package without prefix like 'vvv_'. Must not contain whitespace.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>COPYRIGHT</Name>
      <Type>UserString</Type>
      <Description>The copyright string for the file headers.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>COMPANY</Name>
      <Type>UserString</Type>
      <Description>The company name (for the file information on Windows).</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>MOD_PROD_NAME</Name>
      <Type>UserString</Type>
      <Description>The name of the module as product (for the file information on Windows).</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>CREATION_DATE</Name>
      <Type>SysDate</Type>
      <Description>The date of the creation of the package.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_ORG_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package organelle folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_INT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package interface folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_CFG_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package configuration folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_CFG_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package configuration project used in the Windows vcxproj and sln files of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_COLL_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package organelle collection folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_COLL_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package collection project used in the Windows vcxproj and sln files of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_COMN_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package organelle common folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_MSG_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package message project used in the Windows vcxproj and sln files of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_SYM_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package symbiosis project used in the Windows vcxproj and sln files of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_MOD_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package module folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_MOD_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package module project used in the Windows vcxproj and sln files of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_TEST_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package test project used in the Windows vcxproj and sln files of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>LNX_ORG_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package organelle folder used in the Linux sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_INT_C_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package interface c folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_INT_LANG_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package interface language folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_INT_TEST_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package interface test folder used in the Windows sln file of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>LNX_MOD_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the package module project used in the Linux vcxproj and sln files of msbuild.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_INT_STAT_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the static library c interface project.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>WIN_INT_DLL_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the dynamic library c interface project.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>DOT_NET_SHD_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the .NET shared item interface project.</Description>
    </MacroDefinition>
    <MacroDefinition>
      <Name>DOT_NET_TEST_PROJECT_GUID</Name>
      <Type>SysGuid</Type>
      <Description>The id of the .NET test interface project.</Description>
    </MacroDefinition>
  </MacroDefinitions>
</Template>
